name: spacemoon
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^2.18.0
  firebase_app_check: ^0.2.1+1
  cloud_firestore: ^4.11.0
  firebase_messaging: ^14.7.3
  cloud_functions: ^4.5.2
  firebase_storage: ^11.4.0
  firebase_auth: ^4.12.1
  firebase_crashlytics: ^3.4.8
  firebase_ui_auth: ^1.11.0
  firebase_ui_oauth_google: ^1.2.15
  firebase_ui_oauth_apple: ^1.2.15
  firebase_ui_firestore: ^1.5.13
  firebase_ui_localizations: ^1.9.0

  intl: ^0.18.1

  protobuf: ^3.1.0

  http: ^1.1.2

  go_router: ^12.1.1
  go_router_builder: ^2.3.3

  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.5

  shared_preferences: ^2.2.2

  path_provider: ^2.1.1
  path: ^1.8.3

  flutter_adaptive_scaffold: ^0.1.7+1
  scrollable_positioned_list: ^0.3.8

  flutter_animate: ^4.2.0+1
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1

  rxdart: ^0.27.7

  flutter_link_previewer: ^3.2.2
  flutter_linkify: ^6.0.0

  image_picker: ^1.0.4
  photo_view: ^0.14.0
  video_player: ^2.8.1
  mime: ^1.0.4
  saver_gallery: ^3.0.1
  flutter_svg: ^2.0.9
  lottie: ^2.7.0

  barcode_widget: ^2.0.4

  appflowy_editor: ^2.0.0

  mobile_scanner: ^3.5.2

  flutter_native_splash: ^2.3.7

  moonspace:
    git:
      url: https://github.com/CodeHariK/MoonSpace.git

dependency_overrides:
  moonspace:
    path: ../MoonSpace

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.3
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  riverpod_lint: ^2.1.1

  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

flutter_launcher_icons:
  android: "ic_spacemoon"
  ios: true
  image_path: "assets/images/SpaceMoon.png"
  remove_alpha_ios: true
  min_sdk_android: 27
  web:
    generate: true
    image_path: "assets/images/SpaceMoon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/SpaceMoon.png"
  branding: assets/images/Trademark.png
  color_dark: "#ffffff"
  image_dark: "assets/images/SpaceMoon.png"
  branding_dark: assets/images/Trademark.png

  android_12:
    image: assets/images/SpaceMoon_android.png
    color: "#ffffff"
    branding: assets/images/Trademark.png
    image_dark: assets/images/SpaceMoon_android.png
